### ISSUE TITLE
Rezerwacje

### ISSUE THREAD

**Issue by mateuszgorniak** [netguru-training/team-herrings#6]
Użytkownik powinien móc wysłać rezerwację. 
Rezerwacja:
- date (data godzina rezerwacji)
- customer_id (ref) # zamawiajacy
- user_id (ref) # osoba potwierdzajaca (odrzuci / zaakceptuje)
- table_id (ref) - będzie wybierany dopiero na etapie akceptacji/odrzucenia rezerwacji
- status (accepted/pending/rejected)
  - reject_reason

Administrator może ją odrzucić/zaakceptować.

**Comment by w0st** [comment]
Main functionality done.
