### ISSUE TITLE
Wyciągaj VAT ze zdefiniowanej ceny potrawy, oblicz cenę netto

### ISSUE THREAD

**Issue by mateuszgorniak** [netguru-training/team-herrings#9]
Mock: https://www.evernote.com/l/AVUNxWde62VL5bPGa6nMUcjKeqaJqark5ZQ

Nie zapomnij o speckach.

**Comment by mateuszgorniak** [comment]
Please use my tips to improve code quality @sztosz https://github.com/netguru-training/team-herrings/commit/9bf86466a690c0fdedf01a51c45dfef7bc1544e5

**Comment by sztosz** [comment]
Fixed c44db54e2d76583febdc2a9ad75920f122ba6bb4
